座席管理機能の追加
traPtitech/trap-collection-launcher pull request #52
Opened 2021-12-18 11:42 UTC by anko9801

2021-12-19 02:36 UTC, JichouP requested changes
@anko9801 

- `window.on('close')` だと、ランチャーを閉じないと離席したことになりません:cry: なにか「イイカンジ」に離席判定ができる方法ってないですかね（ゲームを閉じて30秒間なにもしないとか？）
- `koudaisai=true` のときのみ呼び出すようにしてください

2022-08-08 06:27 UTC, anko9801 commented
full screenでsetIgnoreMouseEventsを付けた透過windowを起動してそのマウス/キーボードイベントを取得したものを使うのはどうでしょうか

2022-08-08 07:10 UTC, JichouP commented
@anko9801 
良いかも！
この方向で検証を進めてください！:pray:

2022-09-14 05:32 UTC, anko9801 commented
他アプリに影響なくイベントを発行できました。setIgnoreMouseEventsはマウスイベントの透過に必要かと思っていましたが実際は必要なかったようです:pray:

2022-09-14 06:15 UTC, JichouP commented
検証ありがとうございます
良さそうなので、このまま実装に入ってしまいましょう！
引き続きよろしくお願いします

仕様の詳細がフワッとしてしまっているのですが、実装の前に話し合って決定したかったら教えてください
どちらにせよフィードバックを貰うことにはなると思うので、まずは anko くんの思った通りに実装を進めていっても構いません

2022-10-15 04:25 UTC, anko9801 commented
2分間マウスを動かさなかったときに座っていないと判定するので十分だと思ったのでウィンドウ関連はやめました。

2022-10-15 04:35 UTC, JichouP commented
@anko9801 
よさそう！
コメントもありがとうございます

マージしても大丈夫なやつですか？

2022-10-15 12:59 UTC, anko9801 commented
大丈夫です。

2022-10-15 14:14 UTC, JichouP approved these changes

2022-10-15 14:15 UTC, JichouP commented
@yukikurage 
お願いします！

2022-10-27 14:27 UTC, merged